stages:
  - build
  - deploy

variables:
  IMAGE_BASE_PATH: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG
  INSTANCE_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY


prod_build:
  stage: build
  tags:
    - swarm-manager-test
  script:
    - docker-compose -f docker-compose-prod.yml build
    - docker-compose -f docker-compose-prod.yml push
  only:
    - master

prod_deploy:
  stage: deploy
  tags:
    - swarm-manager-prod
  before_script:
    - docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker stack deploy --with-registry-auth --compose-file=docker-compose-prod.yml --prune ${CI_PROJECT_NAME}
  only:
    - master
