version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: ${IMAGE_BASE_PATH}/front:latest
    networks:
      - studio-expert-swarm

networks:
  studio-expert-swarm:
    external: true

