version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: prod
    command: npm run start_prod
    image: ${IMAGE_BASE_PATH}/web:latest
    networks:
      - studio-expert-swarm


networks:
  studio-expert-swarm:
    external: true
