version: "3.8"

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        CONFIG_NAME: nginx.test
    image: ${IMAGE_BASE_PATH}/web-test:latest
    networks:
      - default
      - studio-expert-swarm
    ports:
      - "4546:80"

  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRGET: test
    command: npm run start_test
    image: ${IMAGE_BASE_PATH}/front-test:latest


networks:
  studio-expert-swarm:
    external: true
