version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        CONFIG_NAME: nginx.test
    image: ${IMAGE_BASE_PATH}/front-test:latest
    networks:
      - studio-expert-swarm

networks:
  studio-expert-swarm:
    external: true

