version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRGET: prod
    command: nuxt start --dotenv .env.prod
    image: ${IMAGE_BASE_PATH}/web:latest


networks:
  studio-expert-swarm:
    external: true
